# -*- coding: UTF-8 -*-
"""
Imports the ERC/Scopus authors TSV (autori_scopus_preferred-name_erc.tsv)
into a MongoDB collection, turning the Panel/Domain and
projectAcronym/projectID/n_progetti columns into nested structures.

DEFAULT: for rows with scopus_author_id, the existing document in the
collection (natural key: scopus_author_id) is compared with the one that
would be generated (ignoring _id and imported_at): if they are identical,
the document is NOT rewritten (no write query, imported_at keeps its
original value). If it differs or doesn't exist yet, an upsert is
performed and imported_at is updated to now.

--force: skips every check. The collection is dropped entirely (indexes
included) and recreated from scratch with all rows of the TSV, each with
a new _id. WARNING: the collections generated by step 02
(erc_ambiguous_surname, etc.) reference this collection's current _id
values via "_id_source" - after a --force here those must be regenerated
too (e.g. with --force on step 02), otherwise they become orphaned.
"""
import argparse
import csv
import os
import sys
from datetime import datetime, timezone
from itertools import zip_longest

from pymongo import MongoClient

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_INPUT = os.path.join(SCRIPT_DIR, "data", "input", "autori_scopus_preferred-name_erc.tsv")
DEFAULT_DB = "scopus-fossr"
DEFAULT_COLLECTION = "erc"


def rel(path):
    """path relative to SCRIPT_DIR, only for display in the help text."""
    return os.path.relpath(path, SCRIPT_DIR)

DOMAIN_LABELS = {
    "LS": "Life Sciences",
    "PE": "Physical sciences & engineering",
    "SH": "Social sciences & humanities",
}


def split_pipe(value):
    if not value:
        return []
    return [v.strip() for v in value.split("|") if v.strip()]


def parse_panel_token(token):
    # standard format: "LS9 - Biotechnology & Biosystems Engineering"
    # synergy format:   "SYG-LS Life Sciences" (no " - ")
    if " - " in token:
        code, label = token.split(" - ", 1)
    else:
        code, label = token.split(" ", 1)
    code = code.strip()
    label = label.strip()

    if code.startswith("SYG-"):
        domain = code.split("-", 1)[1]
    else:
        domain = "".join(ch for ch in code if ch.isalpha())

    domain_label = DOMAIN_LABELS.get(domain, domain)
    return {
        "domain": domain,
        "domain_label": domain_label,
        "panel": code,
        "panel_label": label,
    }


def parse_panels(raw_panel):
    tokens = split_pipe(raw_panel)
    panels = [parse_panel_token(t) for t in tokens]
    domains = list(dict.fromkeys(p["domain"] for p in panels))
    return panels, domains


def parse_projects(raw_acronym, raw_id, context=""):
    acronyms = split_pipe(raw_acronym)
    ids = split_pipe(raw_id)
    if len(acronyms) != len(ids):
        print(
            f"WARNING - projectAcronym/projectID have different lengths ({len(acronyms)} vs {len(ids)}) [{context}]",
            file=sys.stderr,
        )
    projects = [
        {"acronym": acronym, "project_id": project_id}
        for acronym, project_id in zip_longest(acronyms, ids, fillvalue=None)
    ]
    return projects


def build_document(row, source_file):
    panels, domains = parse_panels(row.get("Panel", ""))
    projects = parse_projects(
        row.get("projectAcronym", ""),
        row.get("projectID", ""),
        context=row.get("indexed_name", ""),
    )

    doc = {
        "indexed_name": row.get("indexed_name", "").strip(),
        "given_name": row.get("given_name", "").strip(),
        "surname": row.get("surname", "").strip(),
        "name_in_project_dataset": row.get("nome_dataset_progetti", "").strip(),
        "n_panels": len(panels),
        "panels": panels,
        "n_domains": len(domains),
        "domains": domains,
        "n_projects": len(projects),
        "projects": projects,
        "source_file": source_file,
        "imported_at": datetime.now(timezone.utc),
    }

    auid = row.get("scopus_author_id", "").strip()
    if auid:
        doc["scopus_author_id"] = auid

    return doc


def normalize_for_compare(doc):
    """copy of the document without the fields that are not meaningful
    for the equality comparison (_id, non-deterministic when absent; and
    imported_at, which changes on every run even when content is
    identical)."""
    d = dict(doc)
    d.pop("_id", None)
    d.pop("imported_at", None)
    return d


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-i", "--input",
        default=DEFAULT_INPUT,
        help=f"input TSV file (default: {rel(DEFAULT_INPUT)})",
    )
    parser.add_argument(
        "--db",
        default=DEFAULT_DB,
        help=f"MongoDB database name (default: {DEFAULT_DB})",
    )
    parser.add_argument(
        "--collection",
        default=DEFAULT_COLLECTION,
        help=f"MongoDB collection name (default: {DEFAULT_COLLECTION})",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="skip the 'unchanged' check: drop the whole collection "
             "and recreate it from scratch with all rows of the TSV, all "
             "with a new _id (default: compare and rewrite only what "
             "is new or modified)",
    )
    args = parser.parse_args()

    client = MongoClient()
    db = client[args.db]
    collection = db[args.collection]

    if args.force:
        collection.drop()
        print(f"--force: collection {args.db}.{args.collection} dropped, recreating it from scratch")

    # unique sparse: guarantees uniqueness of scopus_author_id when present,
    # without constraining rows that lack it (the field is simply not saved in that case)
    collection.create_index("scopus_author_id", unique=True, sparse=True)

    source_file = os.path.basename(args.input)

    # existing documents, indexed by scopus_author_id (natural key)
    # (empty after a --force, since the collection was just emptied)
    existing_by_auid = {
        d["scopus_author_id"]: d
        for d in collection.find({"scopus_author_id": {"$exists": True}})
    }

    n_unchanged = 0
    n_upserted = 0
    n_inserted_no_auid = 0
    n_total = 0

    with open(args.input, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            n_total += 1
            doc = build_document(row, source_file)

            if "scopus_author_id" in doc:
                existing = existing_by_auid.get(doc["scopus_author_id"])
                if existing is not None and normalize_for_compare(existing) == normalize_for_compare(doc):
                    n_unchanged += 1
                else:
                    collection.update_one(
                        {"scopus_author_id": doc["scopus_author_id"]},
                        {"$set": doc},
                        upsert=True,
                    )
                    n_upserted += 1
            else:
                collection.insert_one(doc)
                n_inserted_no_auid += 1

            if n_total % 200 == 0:
                print(f"...{n_total} rows processed")

    print(f"\nDone: {n_total} rows total")
    print(f"  unchanged (no write): {n_unchanged}")
    print(f"  upserted (new or modified): {n_upserted}")
    print(f"  inserted (no scopus_author_id): {n_inserted_no_auid}")
    print(f"  db.collection: {args.db}.{args.collection}")


if __name__ == "__main__":
    main()
