# -*- coding: UTF-8 -*-
"""
Builds four collections derived from the "erc" collection, partitioning
all of its documents according to two criteria:

- surname: erc_ambiguous_surname (documents that share "surname",
  case insensitive, with at least one other erc document) / erc_unambiguous_surname
  (all other erc documents).
- surname + initial of given_name: erc_ambiguous_surname_initial (documents
  that share both "surname" and the initial of "given_name", both
  case insensitive, with at least one other erc document) / erc_unambiguous_surname_initial
  (all other erc documents).

In all four collections, the _id of every generated document is
auto-generated by MongoDB; the _id of the source erc document is reported
in the "_id_source" field. Every document reports the document's
domains/panels and a "match_scopus" field with the disambiguation info.

In the two *ambiguous* collections (surname and surname_initial), for
each group of N homonyms all N x N ordered combinations (person,
candidate auid) taken from the group are generated, including the
self-match: each combination is a document with "match_scopus" set to the
candidate auid and a "match" field set to 1 if the candidate auid is the
person's real one, 0 otherwise. In the two *unambiguous* collections there
is instead one document per person (no expansion, no "match" field).

Two filters are applied, in sequence, before forming the homonym groups:

1. MULTI-PANEL FILTER (on by default): erc documents with more than one
   DISTINCT panel (e.g. "LS1" and "PE9") are excluded upfront - they end
   up in none of the four collections and don't even contribute to the
   surname/initial duplicate count. A document with the same panel
   repeated multiple times is instead kept. Use --keep-multipanels to
   disable this filter and consider all erc documents, regardless of
   how many distinct panels they have.

2. PANEL COLLISION FILTER BETWEEN HOMONYMS (always on, cannot be
   disabled): within a group of homonyms (surname, or surname+initial),
   whoever shares a panel with another member of the same group is
   excluded from the combinatorial generation and moved individually to
   erc_unambiguous_surname/_initial (because citation overlap with that
   panel could not distinguish them anyway). The survivors of the group
   (all with different panels from each other), if at least 2 remain,
   form an ambiguous subgroup with the usual N x N combinations; if only
   1 remains, it too is moved to unambiguous (a group of 1 is no longer
   ambiguous).

DEFAULT: each of the four collections is compared (independently of the
others) with what would be generated now: the comparison uses a natural
key that ignores each document's random _id (_id_source for the
*unambiguous* collections; _id_source + candidate auid for the
*ambiguous* ones). If the content matches exactly, that collection is NOT
rewritten; only the collections that turn out to actually differ are
rebuilt from scratch (drop + insert).

--force: skips the comparison for all four collections, which are always
dropped (drop + insert) and rewritten from scratch with new _ids,
regardless of whether the content would have stayed identical.
"""
import argparse
from collections import Counter, defaultdict

from pymongo import MongoClient

DEFAULT_DB = "scopus-fossr"
DEFAULT_SOURCE_COLLECTION = "erc"
DEFAULT_AMBIGUOUS_SURNAME_COLLECTION = "erc_ambiguous_surname"
DEFAULT_UNAMBIGUOUS_SURNAME_COLLECTION = "erc_unambiguous_surname"
DEFAULT_AMBIGUOUS_SURNAME_INITIAL_COLLECTION = "erc_ambiguous_surname_initial"
DEFAULT_UNAMBIGUOUS_SURNAME_INITIAL_COLLECTION = "erc_unambiguous_surname_initial"

DEFAULT_DISAMBIGUATED_BY = "erc_giusy_cordis_horizon"
DEFAULT_DISAMBIGUATION_DB = "erc"
DEFAULT_DISAMBIGUATION_FILE = "autori_scopus_preferred-name_erc.tsv"


def has_multiple_panels(doc):
    panel_codes = {p.get("panel") for p in doc.get("panels", [])}
    return len(panel_codes) > 1


def panel_codes_of(doc):
    return {p.get("panel") for p in doc.get("panels", [])}


def surname_key(doc):
    return doc.get("surname", "").strip().lower()


def surname_initial_key(doc):
    given_name = doc.get("given_name", "").strip()
    initial = given_name[:1].lower() if given_name else ""
    return (surname_key(doc), initial)


def match_scopus_entry(auid, disambiguated_by, disambiguation_db, disambiguation_file):
    return {
        "auid": auid,
        "disambiguated-by": disambiguated_by,
        "disambiguation_db": disambiguation_db,
        "disambiguation_file": disambiguation_file,
    }


def build_document_plain(doc, disambiguated_by, disambiguation_db, disambiguation_file):
    """one document per person (*unambiguous* collections): the person's
    own auid, no combinatorial expansion, no "match" field."""
    auid = doc.get("scopus_author_id")
    match_scopus = [match_scopus_entry(auid, disambiguated_by, disambiguation_db, disambiguation_file)] if auid else []
    return {
        "_id_source": doc["_id"],
        "domains": doc.get("domains", []),
        "panels": [p.get("panel") for p in doc.get("panels", [])],
        "match_scopus": match_scopus,
    }


def build_document_combination(doc, candidate_auid, disambiguated_by, disambiguation_db, disambiguation_file):
    """one document for every (person, candidate auid) of a group of
    homonyms (*ambiguous* collections): "match" is 1 if candidate_auid is
    the person's real auid, 0 otherwise."""
    own_auid = doc.get("scopus_author_id")
    return {
        "_id_source": doc["_id"],
        "domains": doc.get("domains", []),
        "panels": [p.get("panel") for p in doc.get("panels", [])],
        "match_scopus": [match_scopus_entry(candidate_auid, disambiguated_by, disambiguation_db, disambiguation_file)],
        "match": 1 if candidate_auid == own_auid else 0,
    }


def build_ambiguous_combinations(docs, group_key_fn, disambiguated_by, disambiguation_db, disambiguation_file):
    """groups docs by group_key_fn. Within each group with more than one
    document, people who share a panel with another homonym in the same
    group are excluded (citation overlap cannot distinguish them) and
    returned as "demoted"; for the survivors (if at least 2 remain), all
    N x N combinations (person, candidate auid) are generated. Returns
    (generated_documents, number_of_ambiguous_people,
    documents_demoted_to_unambiguous)."""
    groups = defaultdict(list)
    for d in docs:
        groups[group_key_fn(d)].append(d)

    generated = []
    n_people_ambiguous = 0
    demoted = []

    for group in groups.values():
        if len(group) <= 1:
            continue

        panel_owner_count = Counter()
        for d in group:
            for code in panel_codes_of(d):
                panel_owner_count[code] += 1

        def collides(d):
            return any(panel_owner_count[code] > 1 for code in panel_codes_of(d))

        colliding = [d for d in group if collides(d)]
        survivors = [d for d in group if not collides(d)]
        demoted.extend(colliding)

        if len(survivors) <= 1:
            demoted.extend(survivors)
            continue

        n_people_ambiguous += len(survivors)
        candidate_auids = [d.get("scopus_author_id") for d in survivors if d.get("scopus_author_id")]
        for owner in survivors:
            for candidate_auid in candidate_auids:
                generated.append(build_document_combination(
                    owner, candidate_auid, disambiguated_by, disambiguation_db, disambiguation_file
                ))

    return generated, n_people_ambiguous, demoted


def rebuild_collection(collection, documents):
    collection.delete_many({})
    if documents:
        collection.insert_many(documents)


def natural_key_plain(doc):
    return str(doc["_id_source"])


def natural_key_combination(doc):
    auid = doc["match_scopus"][0]["auid"] if doc.get("match_scopus") else None
    return (str(doc["_id_source"]), auid)


def normalize_doc(doc):
    d = dict(doc)
    d.pop("_id", None)
    return d


def collection_matches_target(collection, target_docs, key_fn):
    existing_docs = list(collection.find({}))
    if len(existing_docs) != len(target_docs):
        return False
    existing_by_key = {key_fn(d): normalize_doc(d) for d in existing_docs}
    target_by_key = {key_fn(d): normalize_doc(d) for d in target_docs}
    return existing_by_key == target_by_key


def sync_collection(collection, target_docs, key_fn, force=False):
    """if force is False and the collection's content already matches
    target_docs exactly (by natural key, ignoring _id), nothing is
    written. Otherwise (difference, or force=True) the collection is
    rebuilt from scratch. Returns True if it wrote (rebuilt), False if
    left unchanged."""
    if not force and collection_matches_target(collection, target_docs, key_fn):
        return False
    rebuild_collection(collection, target_docs)
    return True


def main():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--db", default=DEFAULT_DB,
                         help=f"MongoDB database (default: {DEFAULT_DB})")
    parser.add_argument("--source-collection", default=DEFAULT_SOURCE_COLLECTION,
                         help=f"source collection (default: {DEFAULT_SOURCE_COLLECTION})")
    parser.add_argument("--asc", "--ambiguous-surname-collection",
                         dest="ambiguous_surname_collection", default=DEFAULT_AMBIGUOUS_SURNAME_COLLECTION,
                         help=f"destination collection for documents with duplicate surname "
                              f"(default: {DEFAULT_AMBIGUOUS_SURNAME_COLLECTION})")
    parser.add_argument("--usc", "--unambiguous-surname-collection",
                         dest="unambiguous_surname_collection", default=DEFAULT_UNAMBIGUOUS_SURNAME_COLLECTION,
                         help=f"destination collection for documents with NON-duplicate surname "
                              f"(default: {DEFAULT_UNAMBIGUOUS_SURNAME_COLLECTION})")
    parser.add_argument("--asic", "--ambiguous-surname-initial-collection",
                         dest="ambiguous_surname_initial_collection", default=DEFAULT_AMBIGUOUS_SURNAME_INITIAL_COLLECTION,
                         help=f"destination collection for documents with duplicate surname+initial "
                              f"(default: {DEFAULT_AMBIGUOUS_SURNAME_INITIAL_COLLECTION})")
    parser.add_argument("--usic", "--unambiguous-surname-initial-collection",
                         dest="unambiguous_surname_initial_collection", default=DEFAULT_UNAMBIGUOUS_SURNAME_INITIAL_COLLECTION,
                         help=f"destination collection for documents with NON-duplicate surname+initial "
                              f"(default: {DEFAULT_UNAMBIGUOUS_SURNAME_INITIAL_COLLECTION})")
    parser.add_argument("--disambiguated-by", default=DEFAULT_DISAMBIGUATED_BY,
                         help=f"value of the disambiguated-by field (default: {DEFAULT_DISAMBIGUATED_BY})")
    parser.add_argument("--disambiguation-db", default=DEFAULT_DISAMBIGUATION_DB,
                         help=f"value of the disambiguation_db field (default: {DEFAULT_DISAMBIGUATION_DB})")
    parser.add_argument("--disambiguation-file", default=DEFAULT_DISAMBIGUATION_FILE,
                         help=f"value of the disambiguation_file field (default: {DEFAULT_DISAMBIGUATION_FILE})")
    parser.add_argument("--keep-multipanels", action="store_true",
                         help="do not exclude documents with more than one distinct panel "
                              "(default: excluded)")
    parser.add_argument("--force", action="store_true",
                         help="skip the comparison: always drop and rebuild all four "
                              "collections from scratch, even if the content would have "
                              "stayed identical (default: rewrite only the collections that differ)")
    args = parser.parse_args()

    client = MongoClient()
    db = client[args.db]
    source = db[args.source_collection]

    docs = list(source.find(
        {}, {"surname": 1, "given_name": 1, "domains": 1, "panels": 1, "scopus_author_id": 1}
    ))

    n_read = len(docs)
    if not args.keep_multipanels:
        docs = [d for d in docs if not has_multiple_panels(d)]
    n_excluded_multipanel = n_read - len(docs)

    counts_surname = Counter(surname_key(d) for d in docs)
    counts_surname_initial = Counter(surname_initial_key(d) for d in docs)

    def to_plain(d):
        return build_document_plain(d, args.disambiguated_by, args.disambiguation_db, args.disambiguation_file)

    docs_ambiguous_surname, n_people_ambiguous_surname, demoted_surname = build_ambiguous_combinations(
        docs, surname_key, args.disambiguated_by, args.disambiguation_db, args.disambiguation_file
    )
    docs_unambiguous_surname = [
        to_plain(d) for d in docs if counts_surname[surname_key(d)] <= 1
    ] + [to_plain(d) for d in demoted_surname]

    docs_ambiguous_surname_initial, n_people_ambiguous_surname_initial, demoted_surname_initial = build_ambiguous_combinations(
        docs, surname_initial_key, args.disambiguated_by, args.disambiguation_db, args.disambiguation_file
    )
    docs_unambiguous_surname_initial = [
        to_plain(d) for d in docs if counts_surname_initial[surname_initial_key(d)] <= 1
    ] + [to_plain(d) for d in demoted_surname_initial]

    changed_asc = sync_collection(db[args.ambiguous_surname_collection], docs_ambiguous_surname, natural_key_combination, force=args.force)
    changed_usc = sync_collection(db[args.unambiguous_surname_collection], docs_unambiguous_surname, natural_key_plain, force=args.force)
    changed_asic = sync_collection(db[args.ambiguous_surname_initial_collection], docs_ambiguous_surname_initial, natural_key_combination, force=args.force)
    changed_usic = sync_collection(db[args.unambiguous_surname_initial_collection], docs_unambiguous_surname_initial, natural_key_plain, force=args.force)

    def status(changed):
        return "rebuilt" if changed else "unchanged"

    print(f"documents read from {args.db}.{args.source_collection}: {n_read}")
    if not args.keep_multipanels:
        print(f"documents excluded (more than one distinct panel): {n_excluded_multipanel}")
    print(f"documents considered: {len(docs)}")
    print(f"{args.db}.{args.ambiguous_surname_collection}: {len(docs_ambiguous_surname)} documents "
          f"({n_people_ambiguous_surname} ambiguous people) [{status(changed_asc)}]")
    print(f"{args.db}.{args.unambiguous_surname_collection}: {len(docs_unambiguous_surname)} documents [{status(changed_usc)}]")
    print(f"{args.db}.{args.ambiguous_surname_initial_collection}: {len(docs_ambiguous_surname_initial)} documents "
          f"({n_people_ambiguous_surname_initial} ambiguous people) [{status(changed_asic)}]")
    print(f"{args.db}.{args.unambiguous_surname_initial_collection}: {len(docs_unambiguous_surname_initial)} documents [{status(changed_usic)}]")

    print()
    print("=== final report ===")
    print(f"starting elements: {n_read}")
    print()
    print("surname:")
    print(f"  ambiguous people: {n_people_ambiguous_surname}")
    print(f"  documents generated ({args.ambiguous_surname_collection}): {len(docs_ambiguous_surname)}")
    print(f"  non-ambiguous people ({args.unambiguous_surname_collection}): {len(docs_unambiguous_surname)}"
          f" (of which {len(demoted_surname)} demoted due to panel collision)")
    print(f"  excluded (multi-panel): {n_excluded_multipanel}")
    print(f"  total people: {n_people_ambiguous_surname + len(docs_unambiguous_surname) + n_excluded_multipanel}")
    print()
    print("surname_initial:")
    print(f"  ambiguous people: {n_people_ambiguous_surname_initial}")
    print(f"  documents generated ({args.ambiguous_surname_initial_collection}): {len(docs_ambiguous_surname_initial)}")
    print(f"  non-ambiguous people ({args.unambiguous_surname_initial_collection}): {len(docs_unambiguous_surname_initial)}"
          f" (of which {len(demoted_surname_initial)} demoted due to panel collision)")
    print(f"  excluded (multi-panel): {n_excluded_multipanel}")
    print(f"  total people: {n_people_ambiguous_surname_initial + len(docs_unambiguous_surname_initial) + n_excluded_multipanel}")


if __name__ == "__main__":
    main()
